version: '3.8'
services:
#  zookeeper:
#    image: zookeeper:3.7.0
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: confluentinc/cp-kafka:6.2.0
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_NUM_PARTITIONS: 1

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: "dynamodb"
      HOSTNAME_EXTERNAL: "localhost"
      AWS_DEFAULT_REGION: "sa-east-1"
    ports:
      - "4566:4566"